### ISSUE TITLE
User 

### ISSUE THREAD

**Issue by adanna21** [adanna21/workout-app#15]
@teikmeout
 ERROR: POST http://localhost:3000/api/auth/login 500 (Internal Server Error)

```js
{error: {…}, message: "User is not defined"}
error
:
{}
message
:
"User is not defined"
__proto__
:
Object

```

What we have tried: checked passport, local, auth-helpers, user controller, user model, all are in order and still getting this error when i try to log in

**Comment by teikmeout** [comment]
Issue fixed! please close this ticket 👍
